.config/*

[macOS] .config/clangd => Library/Preferences/clangd

.config/claude/* => .claude/
.config/codex/* => .codex/

.config/lgogdownloader/*

[macOS] .config/sublime-text => Library/Application Support/Sublime Text
[macOS] .config/sublime-merge => Library/Application Support/Sublime Merge

.local/bin/*
.ssh/*
.*

[macOS] Library/**

the-dot.sh => .local/bin/
